version: '2.1'
services:
    api-zap:
        image: api-zap
        build: .
        volumes:
            - .:/api-zap
            - node_modules:/api-zap/node_modules
        ports: 
            - 3000:3333
volumes:
    node_modules: {}